// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbUser = process.env["DB_USER"] || "postgres";
const dbPass = process.env["DB_PASS"] || "postgres";
const dbHost = process.env["DB_HOST"] || "localhost";
const dbPort = process.env["DB_PORT"] || "5432";
const dbName = process.env["DB_NAME"] || "postgres";

let dbUrl = process.env["DATABASE_URL"];
if (!dbUrl || dbUrl.includes("${")) {
  dbUrl = `postgresql://${dbUser}:${dbPass}@${dbHost}:${dbPort}/${dbName}?schema=public`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
